version: "3.8"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'classroom'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./migrator/dump.sql:/docker-entrypoint-initdb.d/dump.sql
