version: "3.8"

services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./migrator/dump.sql:/docker-entrypoint-initdb.d/dump.sql
